import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import ReduxProvider from "@/components/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-primary`} cz-shortcut-listen="true">
        <ReduxProvider>
          <div className="relative">
            <Navbar />
          </div>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
